In [65]:
import sys

n = int(input())

n_2 = 0
n_1 = 1

divider = 1000000007

for i in range(n-1):
    n_1, n_2 = n_1 + n_2, n_1
    if n_2 >= divider:
        n_1 %= divider
        n_2 %= divider


print(str(n_1))

1184550596


In [66]:
import sys

n = int(input())

dp = [None] * (n + 1)
dp[:2] = [0, 1] 

def my_func(n):
    if dp[n] != None:
        result = dp[n]
    else:
        result = my_func(n-1) + my_func(n-2)
        dp[n] = result

    return result

result = my_func(n)
divider = 1000000007
result = result % divider

print(str(result))

184550589


In [72]:
dp[40]*2

204668310

In [71]:
dp[40]*2 % divider

204668310

In [67]:
dp

[0,
 1,
 1,
 2,
 3,
 5,
 8,
 13,
 21,
 34,
 55,
 89,
 144,
 233,
 377,
 610,
 987,
 1597,
 2584,
 4181,
 6765,
 10946,
 17711,
 28657,
 46368,
 75025,
 121393,
 196418,
 317811,
 514229,
 832040,
 1346269,
 2178309,
 3524578,
 5702887,
 9227465,
 14930352,
 24157817,
 39088169,
 63245986,
 102334155,
 165580141,
 267914296,
 433494437,
 701408733,
 1134903170,
 1836311903,
 2971215073,
 4807526976,
 7778742049,
 12586269025,
 20365011074,
 32951280099,
 53316291173,
 86267571272,
 139583862445,
 225851433717,
 365435296162,
 591286729879,
 956722026041,
 1548008755920,
 2504730781961,
 4052739537881,
 6557470319842,
 10610209857723,
 17167680177565,
 27777890035288,
 44945570212853,
 72723460248141,
 117669030460994,
 190392490709135,
 308061521170129,
 498454011879264,
 806515533049393,
 1304969544928657,
 2111485077978050,
 3416454622906707,
 5527939700884757,
 8944394323791464,
 14472334024676221,
 23416728348467685]

In [1]:
import sys

# input = sys.stdin.readline
# print = sys.stdout.write

n = int(input())

dp = [None] * (n + 1)
dp[:2] = [0, 1] 

def my_func(n):
    if dp[n] != None:
        result = dp[n]
    else:
        result = my_func(n-1) + my_func(n-2)
        dp[n] = result

    return result

result = my_func(n)
divider = 1000000007
result = result % divider

print(str(result))

517691607


In [1]:
n = 1000
dp = [None] * (n + 1)
dp[:2] = [0, 1] 
def my_func(n):
    if dp[n] != None:
        result = dp[n]
    else:
        result = my_func(n-1) + my_func(n-2)
        dp[n] = result

    return result

In [2]:
divider = 1000000007

In [3]:
a = my_func(1000)

In [4]:
a % divider

517691607

In [44]:
n_2 = 0
n_1 = 1
target = 0

for i in range(16):
    n_1, n_2 = n_1 + n_2, n_1

print(n_2, n_1)

987 1597


In [36]:
n_2

55

In [37]:
n_1

89

In [45]:
3으로 나눈 나머지

SyntaxError: invalid syntax (3971337096.py, line 1)

In [46]:
17 % 3

2

In [47]:
8 % 3

2

In [49]:
5 % 3

2

In [50]:
6 % 3

0

In [51]:
11 % 3

2

In [48]:
9 % 3

0

In [60]:
divider = 17

In [61]:
1597 % divider

16

In [ ]:
temp_list = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597]
                                       5 2    7   9

In [ ]:
                                  13(0) 4 0 4 4 8(144) 12 3 15 1 

In [ ]:
list(range(2)

range(0, 2)

In [14]:
list(range(1))

[0]

In [91]:
21 % 16

5

In [ ]:
1134903170%

In [16]:
divider

1000000007

In [17]:
(433494437 + 701408733) % divider

134903163

In [9]:
433494437 + 701408733

1134903170

In [11]:
1134903170 % divider

134903163

In [10]:
1134903170 + 701408733

1836311903

In [8]:
dp[44]

701408733

In [7]:
len(dp)

45

In [6]:
dp

[0,
 1,
 1,
 2,
 3,
 5,
 8,
 13,
 21,
 34,
 55,
 89,
 144,
 233,
 377,
 610,
 987,
 1597,
 2584,
 4181,
 6765,
 10946,
 17711,
 28657,
 46368,
 75025,
 121393,
 196418,
 317811,
 514229,
 832040,
 1346269,
 2178309,
 3524578,
 5702887,
 9227465,
 14930352,
 24157817,
 39088169,
 63245986,
 102334155,
 165580141,
 267914296,
 433494437,
 701408733]

In [94]:
n = 17

n_2 = 0
n_1 = 1

divider = 17

for i in range(n-1):
    n_1, n_2 = n_1 + n_2, n_1
    if n_2 >= divider:
        n_1 %= divider
        n_2 %= divider

In [1]:
s = "1,000,000,000,000,000,000"
n = int(s.replace(",", ""))
print(n)

1000000000000000000


In [3]:
n = 1000

In [4]:
dp = [0,
 1,
 1,
 2,
 3,
 5,
 8,
 13,
 21,
 34,
 55,
 89,
 144,
 233,
 377,
 610,
 987,
 1597,
 2584,
 4181,
 6765,
 10946,
 17711,
 28657,
 46368,
 75025,
 121393,
 196418,
 317811,
 514229,
 832040,
 1346269,
 2178309,
 3524578,
 5702887,
 9227465,
 14930352,
 24157817,
 39088169,
 63245986,
 102334155,
 165580141,
 267914296,
 433494437,
 701408733,
 ]

divider = 1000000007

if n <= 44:
    result = dp[n]
else:
    n_2, n_1 = dp[-2], dp[-1]
    for i in range(n-44):
        n_1, n_2 = n_1 + n_2, n_1
        if n_1 >= divider:
            n_1 %= divider

print(str(n_1))

517691607


In [ ]:
13 21
34 = 13 +21
55 = 13 + 21 + 21
89 = 13+21+21 +13 + 21

In [5]:
13+ 13 + 21 +21

68

In [11]:
dp = [0,
 1,
 1,
 2,
 3,
 5,
 8,
 13,
 21,
 34,
 55,
 89,
 144,
 233,
 377,
 610,
 987,
 1597,
 2584,
 4181,
 6765,
 10946,
 17711,
 28657,
 46368,
 75025,
 121393,
 196418,
 317811,
 514229,
 832040,
 1346269,
 2178309,
 3524578,
 5702887,
 9227465,
 14930352,
 24157817,
 39088169,
 63245986,
 102334155,
 165580141,
 267914296,
 433494437,
 701408733,
 ]

In [ ]:
a = [1, 2, 3]


[1, 2]

In [24]:
temp_list = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597]
divider = 7
# dp -> temp_list[:6] -> 6개
my_len = 6

In [ ]:
#35 -> 17 + 18 -> 8+9 + 9+9 -> 4+4+4+5 + 4+5 + 4+5

In [20]:
n = 35

In [55]:
nums = []
temp = []
stack = [n]
my_sum = 0
while stack:
    my_num = stack.pop()
    n1 = my_num // 2
    n2 = my_num - n1

    if n1 < my_len:
        my_sum += dp[n1]
        nums.append(dp[n1])
        temp.append(n1)
    else:
        stack.append(n1)

    if n2 < my_len:
        my_sum += dp[n2]
        nums.append(dp[n2])
        temp.append(n2)
    else:
        stack.append(n2)        

In [56]:
my_sum % 7

2

In [54]:
my_sum

24

In [53]:
temp

[4, 5, 4, 5, 4, 5, 4, 4]

In [46]:
nums

[3, 5, 3, 5, 3, 5, 3, 3]

In [50]:
dp[35] % divider

2

In [57]:
divider = 1000000007

In [17]:
dp[4] * 5

15

In [18]:
dp[5] * 3

15

In [19]:
30 % 7

2

In [ ]:
n = 35
# 17 + 18 -> 8+9 + 9+9 -> 4+4+4+5 + 4+5 + 4+5

In [58]:
divider = 1000000007

In [59]:
dp = [0,
 1,
 1,
 2,
 3,
 5,
 8,
 13,
 21,
 34,
 55,
 89,
 144,
 233,
 377,
 610,
 987,
 1597,
 2584,
 4181,
 6765,
 10946,
 17711,
 28657,
 46368,
 75025,
 121393,
 196418,
 317811,
 514229,
 832040,
 1346269,
 2178309,
 3524578,
 5702887,
 9227465,
 14930352,
 24157817,
 39088169,
 63245986,
 102334155,
 165580141,
 267914296,
 433494437,
 701408733,
 ]

In [ ]:
n = 44

In [61]:
dp[44]

701408733

In [62]:
dp[22] + dp[22]

35422

In [1]:
fn = 1
fn_1 = 1
fn_2 = 0

In [1]:
def my_func(matrix: list[list[int]]) -> int:
    matrix_1 = [
        [1, 1],
        [1, 0]
    ]
    matrix_2 = matrix
    matrix_3 = [
        [matrix_1[0][0]*matrix_2[0][0] + matrix_1[0][1]*matrix_2[1][0]],
        [matrix_1[1][0]*matrix_2[0][0] + matrix_1[1][1]*matrix_2[1][0]],
    ]

    return matrix_3

matrix = [
    [1],
    [0]
]



In [2]:
n = 1

matrix = [
    [1],
    [0]
]
for i in range(n-1):
    matrix = my_func(matrix)

divider = 1000000007
print(matrix[0][0] % divider)

1


In [9]:
import numpy as np

temp = np.array(
    [
        [1, 1],
        [1 ,0]
    ]
)
temp_2 = np.array(
    [
        [1, 1],
        [1 ,0]
    ]
)

temp_2 = np.dot(temp_2, temp)
print(temp_2)

[[2 1]
 [1 1]]


In [10]:
temp_2 = np.dot(temp_2, temp)
print(temp_2)

[[3 2]
 [2 1]]


In [11]:
temp_2 = np.dot(temp_2, temp)
print(temp_2)

[[5 3]
 [3 2]]


In [ ]:
# 7^4 => 7^2 * 7^2
# 7^8 => 7^4 * 7^4
# 7^16 => 7^8 * 7^8 => 7^4 * 7^4 * 7^4 * 7^4 => 7^2 * 7^2 * 7^2 * 7^2 * 7^2 * 7^2 * 7^2 * 7^2

# 7^17 => 7 * 7^16

# 7^30 => 7^15 * 7^15 => 7^15 * 7^7 * 7^8
# 31 => 1 + 15 + 15 => 1 + 15 + (1 + 7 + 7) => 1 + 15 + (1 + 7 + (1 + 3 + 3)) => 1 + 15 + (1 + 7 + (1 + 3 + (1 + 1 + 1)))

In [19]:
answer = 7**31
print(answer)

157775382034845806615042743


In [18]:
answer_2 = 1
for i in range(31):
    answer_2 *= 7

print(answer_2)

157775382034845806615042743


In [23]:
31 % 2

1

In [31]:
1 // 2

0

In [32]:
1 % 2

1

In [82]:
n = 1000
queue = [n-1]
result = []

while True:
    x = queue.pop()
    if x % 2 == 0:
        result.append((x//2, 0))
    else:
        result.append((x//2, 1))
    
    queue.append(x//2)
    if x//2 == 1:
        break

In [50]:
result, queue

([(9, 0), (4, 1), (2, 0), (1, 0)], [1])

In [100]:
n = 1
n = n-1
queue = [n]
result = []

while True:
    x = queue.pop()
    if x <= 1:
        break
    if x % 2 == 0:
        result.append((x//2, 0))
    else:
        result.append((x//2, 1))
    
    queue.append(x//2)
    if x//2 == 1:
        break

In [106]:
a = 1_00_000

In [109]:
3 ** 8

6561

In [110]:
bin(8)

'0b1000'

In [118]:
res = 1
A = 3
print(A)

3


In [119]:
A = A * A
print(A)

9


In [120]:
A = A * A
print(A)

81


In [115]:
res = res * A

In [116]:
res

81

In [ ]:
bin(8)
2^8
a = 2


'0b1000'

In [107]:
a

100000

In [101]:
result

[]

In [102]:
divider = 1000000007

def multiply_matrices(mat_a: list[list[int]], mat_b: list[list[int]]) -> list[list[int]]:
    product = [
        [(mat_a[0][0]*mat_b[0][0] + mat_a[0][1]*mat_b[1][0]) % divider, (mat_a[0][0]*mat_b[0][1] + mat_a[0][1]*mat_b[1][1]) % divider],
        [(mat_a[1][0]*mat_b[0][0] + mat_a[1][1]*mat_b[1][0]) % divider, (mat_a[1][0]*mat_b[0][1] + mat_a[1][1]*mat_b[1][1]) % divider]
    ]

    return product

def apply_matrix_to_vector(matrix: list[list[int]]) -> list[list[int]]:
    vector = [
        [1],
        [0]
    ]
    result = [
        [matrix[0][0]*vector[0][0] + matrix[0][1]*vector[1][0]],
        [matrix[1][0]*vector[0][0] + matrix[1][1]*vector[1][0]],
    ]

    return result

In [103]:
init_matrix = [
    [1, 1],
    [1, 0]
]
matrix = init_matrix.copy()

for _, add_one in result[::-1]:
    if add_one:
        matrix = multiply_matrices(multiply_matrices(matrix, matrix), init_matrix)
    else:
        matrix = multiply_matrices(matrix, matrix)

apply_matrix_to_vector(matrix)

[[1], [1]]

In [ ]:
def my_func(matrix: list[list[int]]) -> int:
    matrix_1 = [
        [1, 1],
        [1, 0]
    ]
    matrix_2 = matrix
    matrix_3 = [
        [matrix_1[0][0]*matrix_2[0][0] + matrix_1[0][1]*matrix_2[1][0]],
        [matrix_1[1][0]*matrix_2[0][0] + matrix_1[1][1]*matrix_2[1][0]],
    ]

    return matrix_3

matrix = [
    [1],
    [0]
]



In [55]:
answer_3

1628413597910449

In [48]:
result

[(8, 0), (4, 0), (2, 0), (1, 0)]

In [47]:
answer_3

33232930569601

In [42]:
result, queue

([(8, 0), (4, 0), (2, 0), (1, 0)], [1])

8 + 4 + 2 + 1 + 1

In [40]:
result, queue

([(15, 1), (7, 1), (3, 1), (1, 1)], [1])

In [ ]:
1 + 15 + (1 + 7 + (1 + 3 + (1 + 1 + 1)))